[package]
name = "astridyz/celesta"
description = "A event-driven ECS for Roblox applied in a library"
license = "MIT"
authors = ["Astrid"]
version = "1.0.2"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"